# Generated by Django 2.2 on 2020-10-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figure',
            old_name='title',
            new_name='object',
        ),
        migrations.AddField(
            model_name='figure',
            name='patent_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
