# Generated by Django 2.2 on 2020-11-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0002_auto_20201018_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='aspect',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='figure',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
