# Generated by Django 2.2 on 2020-11-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0003_auto_20201117_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='imagePath',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
