# Generated by Django 2.2 on 2020-11-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0003_auto_20201117_0236'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_figures', models.ManyToManyField(related_name='saved_by', to='figure.Figure')),
            ],
        ),
    ]
