# Generated by Django 2.2 on 2020-10-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0002_auto_20201016_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='code',
            field=models.CharField(default='hHZISUgWFhhCQDl', max_length=15),
        ),
    ]
