# Generated by Django 2.2 on 2020-10-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0003_email_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='code',
            field=models.CharField(default='OHpBwEfvQllNDbv', max_length=15),
        ),
    ]
