# Generated by Django 2.2 on 2020-11-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0004_auto_20201018_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='code',
            field=models.CharField(default='gorLPeBZBXEfmEM', max_length=15),
        ),
    ]
