# Generated by Django 2.2 on 2020-11-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0006_auto_20201117_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='code',
            field=models.CharField(default='zyatZapxVevPMAo', max_length=15),
        ),
    ]
