# Generated by Django 2.2 on 2020-12-15 01:29

from django.db import migrations, models
import email_verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0008_auto_20201117_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='code',
            field=models.CharField(default=email_verification.models.generate_random_verification_code, max_length=15),
        ),
    ]
